server:
  port: 8080
spring:
  application:
    name: drone
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dronedb
    username: root
    password: 1qaz@WSX
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
springdoc:
  packagesToScan: com.drone